### ISSUE TITLE
Konfigurationsseite wird nicht geöffnet nach Update auf V1.1.1

### ISSUE THREAD

**Issue by Steff42** [ioBroker/ioBroker.eventlist#110]
Hallo,
ich habe auf die Version 1.1.1 aktualisiert und nun kann die Konfiguration (Schraubenschlüssel) in der Instanzansicht nicht mehr geöffnet werden . Auch beim Klicken auf Ereignisse in der Sidebar passiert nichts mehr. Es erscheint in der Chrome Dev-Konsole die folgende Fehlermeldung:

`index.js:16 iobroker.eventlist@1.1.1 using theme "blue"
Prompt.js:15 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:16 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:17 Help us to create open source project with reactJS!
Prompt.js:18 See you :)
socket.io.js:66 [2022-11-02T16:00:33.670Z] Try to connect
instrument.ts:123 Translate: Clear filter
instrument.ts:123 TypeError: Cannot read properties of undefined (reading 'match')
    at List.js:771:59
    at Array.map (<anonymous>)
    at n.value (List.js:765:26)
    at n.value (List.js:881:42)
    at Zs (react-dom.production.min.js:204:189)
    at Es (react-dom.production.min.js:203:149)
    at Cc (react-dom.production.min.js:292:172)
    at yl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at ol (react-dom.production.min.js:271:88)
    at al (react-dom.production.min.js:268:429)
    at x (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:123
fs @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
No @ react-dom.production.min.js:144
wc @ react-dom.production.min.js:262
yc @ react-dom.production.min.js:260
bc @ react-dom.production.min.js:259
(anonym) @ react-dom.production.min.js:283
_l @ react-dom.production.min.js:281
al @ react-dom.production.min.js:270
x @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
List.js:771 Uncaught TypeError: Cannot read properties of undefined (reading 'match')
    at List.js:771:59
    at Array.map (<anonymous>)
    at n.value (List.js:765:26)
    at n.value (List.js:881:42)
    at Zs (react-dom.production.min.js:204:189)
    at Es (react-dom.production.min.js:203:149)
    at Cc (react-dom.production.min.js:292:172)
    at yl (react-dom.production.min.js:280:389)
    at gl (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at ol (react-dom.production.min.js:271:88)
    at al (react-dom.production.min.js:268:429)
    at x (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ List.js:771
value @ List.js:765
value @ List.js:881
Zs @ react-dom.production.min.js:204
Es @ react-dom.production.min.js:203
Cc @ react-dom.production.min.js:292
yl @ react-dom.production.min.js:280
gl @ react-dom.production.min.js:280
ml @ react-dom.production.min.js:280
ol @ react-dom.production.min.js:271
al @ react-dom.production.min.js:268
x @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14`

Fehler tritt auf mit Chrome 106.0.5249.121
Bei Edge 107.0.1418.26 ebenfalls mit einem Unterschied, hier kann wenigstens die Konfiguration geöffnet werden.

Nach Downgrade auf Version 1.0.1 kann die Konfiguration und auch Eventliste aus der Sidebar geöffnet werden.

Node 16.16.0
NPM 8.11.0
JS-Engine 6.0.0
JS-Controller 4.0.23
Admin 6.2.21
Betriebssystem Debian 

Gruß Steffen

**Comment by Steff42** [comment]
Nach Update auf Version 1.2.0 ist der Fehler weg!

Gruß Steffen

Issue kann also geschlossen werden.
